language: groovy

jdk:
- oraclejdk7

before_script:
- "export DISPLAY=:99.0" 
- "sh -e /etc/init.d/xvfb start"

before_install:
- sudo rm -rf ~/.gvm
- sudo curl -s get.gvmtool.net > ~/install_gvm.sh
- sudo chmod 775 ~/install_gvm.sh
- sudo ~/install_gvm.sh
- sudo echo sdkman_auto_answer=true > ~/.sdkman/etc/config
- sudo source "/home/travis/.sdkman/bin/sdkman-init.sh"
- sudo sdk install grails 2.1.5

branches:
  only:
    - master

script: grails -Dgeb.env=firefox test-app functional:cucumber --non-interactive --stacktrace
